config/routes.rb
Rails.application.routes.draw do

  root 'searches#home'
  resources :searches

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #omniauth callback
  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'

    resources :users  do
      resource :reviews, only: [:new, :create, :index, :show]
    end

    resources :cocktail_bars  do
      resource :favs
    end

    resources :cocktail_bars  do
      resource :reviews, only: [:new, :create, :index]
    end

  resources :favs
  resources :reviews
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/fav.rb
class Fav < ApplicationRecord
  belongs_to :user
  belongs_to :cocktail_bar
  validates :user, :cocktail_bar, presence: true
end

app/controllers/favs_controller.rb
class FavsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    @favs = Fav.all
  end

  def new
    if params[:cocktail_bar_id] && @cocktail_bar = CocktailBar.find_by_id(params[:cocktail_bar_id])
      @fav = @cocktail_bar.favs.build
    else
      @error = "That fav doesn't exist" if params[:cocktail_bar_id]
      @fav = Fav.new
    end
  end

  def create
    @cocktail_bar = CocktailBar.find(params[:cocktail_bar_id])
    @fav = current_user.favs.build
    @fav[:cocktail_bar_id] = @cocktail_bar[:id]
    if @fav.save
      redirect_to favs_path
    else
      flash[:error] = "We were unable to add this location to your favorites, please try again"
      redirect_to current_user
    end
  end

  def destroy
    @fav = Fav.find_by(params[:cocktail_id])
    @fav.destroy
    redirect_to favs_path
  end

  private

end

app/helpers/favs_helper.rb
module FavsHelper
end

app/views/favs/_edit.html.erb
<%= button_to "Remove as a Fav", cocktail_bar_favs_path(params[:id]), :method => :delete %>

app/views/favs/_new.html.erb
<%= form_tag cocktail_bar_favs_path(cocktail_bar.id) do %>
  <%= submit_tag "Make me a Fav", class: "btn-small" %>
<% end %>

app/views/favs/index.html.erb
<h1>My Favs</h1>

<ol>
<% @favs.each do |f| %>
  <% if f.user == current_user %>
    <li><%= link_to f.cocktail_bar.name, cocktail_bar_path(f.cocktail_bar) %> - <%= f.cocktail_bar.address %></li>
  <% end %>
<% end %>
</ol>