config/routes.rb
Rails.application.routes.draw do

  root 'searches#home'
  resources :searches

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #omniauth callback
  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'

    resources :users  do
      resource :reviews, only: [:new, :create, :index, :show]
    end

    resources :cocktail_bars  do
      resource :favs
    end

    resources :cocktail_bars  do
      resource :reviews, only: [:new, :create, :index]
    end

  resources :favs
  resources :reviews
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cocktail_bars
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def create
    @search = Search.create(query: params[:query], user: current_user)
    if CocktailBar.yelp_search_result(params[:query], @search) == "error"
      redirect_to root_path
    else
      @search.save
      redirect_to @search
    end
  end

  def show
    @search = Search.find(params[:id])
  end

  private
  def search_params
    params.require(:query).permit(:query)
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/home.html.erb
<h1>Welcome to Tipsy!</h1>
<br>

<%= form_tag(searches_path, method: :post) do %>
<%= label_tag(:search, "Enter a City to view cocktail bars:") %>
<br>
<%= text_field_tag(:query, nil, class: 'search-text', placeholder: 'Chicago, IL') %>
<%= submit_tag "Find Cocktail Bar", class: 'btn btn-primary'%>
<% end %>

app/views/searches/show.html.erb
<h2>Search Show Page</h2>

<ol>
<% @search.cocktail_bars.each do |cocktail_bar| %>

  <%= render partial: 'cocktail_bars/cocktail_bar', locals: {cocktail_bar: cocktail_bar} %>

<% end %>
</ol>