config/routes.rb
Rails.application.routes.draw do

  root 'searches#home'
  resources :searches

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #omniauth callback
  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'

    resources :users  do
      resource :reviews, only: [:new, :create, :index, :show]
    end

    resources :cocktail_bars  do
      resource :favs
    end

    resources :cocktail_bars  do
      resource :reviews, only: [:new, :create, :index]
    end

  resources :favs
  resources :reviews
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    # if params[:cocktail_bar_id] && @cocktail_bar = CocktailBar.find_by_id(params[:cocktail_bar_id])
      # @review = @cocktail_bar.reviews
    # else
      # @error = "That review doesn't exist" if params[:cocktail_bar_id]
      @reviews = Review.all
    # end
  end

  def new
    if params[:cocktail_bar_id] && @cocktail_bar = CocktailBar.find_by_id(params[:cocktail_bar_id])
      @review = @cocktail_bar.reviews.build
    else
      @error = "That review doesn't exist" if params[:cocktail_bar_id]
      @review = Review.new
    end
  end

  def create
    @cocktail_bar = CocktailBar.find(params[:cocktail_bar_id])
    @review = current_user.reviews.build(review_params)
    @review[:cocktail_bar_id] = @cocktail_bar[:id]
    if @review.save
      redirect_to @review #maybe route to cocktail_bar instead. After finishing CB
    else
      byebug
      render :new
    end
  end

  def show
    if params[:id]
      @review = Review.find(params[:id])
    else
      @review = Review.find_by(user_id: params[:user_id])
    end
  end

  def edit
    @review = Review.find_by(user_id: params[:id])
  end

  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    if @review.save
      redirect_to @review
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end

  private

  def review_params
    params.require(:review).permit(:title, :comment, :rating, :user_id, :cocktail_bar_id)
  end


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<h1>Edit This Review</h1>

<%= form_with model: @review, local: true do |f| %>
  <%= f.label "title:" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label "comment:" %>
  <%= f.text_field :comment %>
  <br>
  <%= f.label "rating:" %>
  <%= f.number_field :rating, step: 0.5 %>
  <br>
  <%= f.submit "Edit" %>
<% end %>

<%= link_to "Delete", @review, method: "delete" %>

app/views/reviews/index.html.erb
<h1>My Reviews</h1>

<ol>
<% @reviews.each do |r| %>
  <% if r.user == current_user %>
    <li><%= r.cocktail_bar.name %> - <%= link_to r.title.capitalize, review_path(r) %></li>
  <% end %>
<% end %>
</ol>

app/views/reviews/new.html.erb
<% if logged_in? %>
  <h2>Make a new review for <%= @cocktail_bar.name %>:</h2>

<%= form_with(model:[@cocktail_bar, @review]) do |f| %>
  <%= f.label "title:" %>
  <%= f.text_field :title %>
  <br>
  <%= f.label "comment:" %>
  <%= f.text_area :comment %>
  <br>
  <%= f.label "rating:" %>
  <%= f.number_field :rating, step: 0.5 %>
  <br>
  <%= f.submit "Submit" %>
  <% end %>


  <% else %>
  <p>You must be <%= link_to 'logged in', login_path %> to leave a review!</p>

<% end %>

app/views/reviews/show.html.erb
<% if !logged_in? %>
  <%= redirect_to login_path %>
<% else %>
<h2><%= @review.cocktail_bar.name %>'s Review </h2>
<p>
Title: <%= @review.title.capitalize %>
<br>
Comment: <%= @review.comment.capitalize %>
<br>
Rating <%= @review.rating %>
<br>
Created by: <%= link_to @review.user.username, user_path(@review.user_id) %> on <%= @review.created_at.strftime("%m/%d/%y") %>
<br>
<br>
<%= link_to "Edit this review", edit_review_path(@review.user_id) %>
</p>
<%= link_to "Make this location a fav", cocktail_bar_path(@review.cocktail_bar_id) %>

<% end %>