config/routes.rb
Rails.application.routes.draw do

  root 'searches#home'
  resources :searches

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  #omniauth callback
  get '/auth/google_oauth2/callback', to: 'sessions#google_auth'

    resources :users  do
      resource :reviews, only: [:new, :create, :index, :show]
    end

    resources :cocktail_bars  do
      resource :favs
    end

    resources :cocktail_bars  do
      resource :reviews, only: [:new, :create, :index]
    end

  resources :favs
  resources :reviews
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Tipsy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tipsy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <!-- <%= render 'layouts/navbar' %> -->

  <body
    <div>
      <% if logged_in? %>
      <%= link_to "Home Page", root_path %> |
      <%= link_to "My Page", user_path(current_user) %> |
      <%= link_to "View My Reviews", reviews_path %> |
      <%= link_to "View My Favorites", favs_path %> |
      <%= link_to "Log Out", logout_path, method: "delete" %>
      <% else %>
      <%= link_to "Log In", login_path %> |
      <%= link_to "Sign Up", signup_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>